version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: '' # Senha vazia

  db:
    image: mysql:5.7
    container_name: yii_db
    environment:
      MYSQL_ROOT_PASSWORD: '' # Senha vazia
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # Permite senha vazia
      MYSQL_DATABASE: yii2basic
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db_data:
    driver: local