name: Yii2 Continuous Integration

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0 # Adjust to your MySQL version
        env:
          MYSQL_ROOT_PASSWORD: '' # Replace with your MySQL root password or use secrets
          MYSQL_DATABASE: yii2basic
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pdo, mysql, mbstring, xml, ctype, tokenizer, intl, gd

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Grant execute permissions to yii
      run: chmod +x yii

    - name: Generate Application Key
      run: ./yii key

    - name: Create Test Database
      run: mysql -h 127.0.0.1 -u root -e "CREATE DATABASE IF NOT EXISTS yii2basic;"

    - name: Apply Migrations
      run: ./yii migrate --interactive=0 --env=test