name: Yii2 Continuous Integration

on:
  push:
    branches:
      - main # Or your main branch
      - develop # Or your develop branch
  pull_request:
    branches:
      - main
      - develop

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Or your required PHP version
          extensions: pdo, mysql, mbstring, curl, gd, zip
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer update --no-interaction --no-dev

      - name: Run Backend Tasks
        run: |
          echo "Running backend tasks..."
          sleep 5 # Simulate backend tasks (replace with actual commands)
          echo "Backend tasks completed."

  build-docker-image:
    runs-on: ubuntu-latest
    needs: [backend] # Depends on backend job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build Docker Image
        run: |
          echo "Running Step 2: Building Docker image..."
          docker-compose build -d # Build your Docker image
          echo "Docker image built."