name: Yii2 Build and Test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Adjust to your required PHP version
        extensions: pdo, mysql, mbstring, xml, ctype, tokenizer, intl, gd # Add needed extensions

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Copy .env.example to .env
      run: cp .env.example .env

    # - name: Grant execute permissions to yii
    #   run: chmod +x yii

    # - name: Generate Application Key
    #   run: ./yii key

    - name: Create Test Database (if needed)
      run: |
        mysql -e "CREATE DATABASE IF NOT EXISTS yii2basic_test;"
        mysql -e "GRANT ALL PRIVILEGES ON yii2basic_test.* TO 'root'@'localhost';"
        mysql -e "FLUSH PRIVILEGES;"
      env:
        MYSQL_ROOT_PASSWORD: '' # Set your MySQL root password if needed

    - name: Apply Migrations if possible
      run: ./yii migrate --interactive=0 --env=test